USE [master]
GO

/****** Object:  Database [projet]    Script Date: 11/2/2021 8:56:39 PM ******/
CREATE DATABASE [projet]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Yassine', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Yassine.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Yassine_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Yassine_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [projet].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [projet] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [projet] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [projet] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [projet] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [projet] SET ARITHABORT OFF 
GO

ALTER DATABASE [projet] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [projet] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [projet] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [projet] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [projet] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [projet] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [projet] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [projet] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [projet] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [projet] SET  DISABLE_BROKER 
GO

ALTER DATABASE [projet] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [projet] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [projet] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [projet] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [projet] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [projet] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [projet] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [projet] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [projet] SET  MULTI_USER 
GO

ALTER DATABASE [projet] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [projet] SET DB_CHAINING OFF 
GO

ALTER DATABASE [projet] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [projet] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [projet] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [projet] SET QUERY_STORE = OFF
GO

ALTER DATABASE [projet] SET  READ_WRITE 
GO

